#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       opencc
# >> macros
# << macros

Summary:    Conversion between Traditional and Simplified Chinese
Version:    1.0.3
Release:    1
Group:      Development/Languages/C++
License:    Apache
URL:        http://github.com/BYVoid/OpenCC
Source:    %{name}-%{version}.tar.gz

BuildRequires:   make
BuildRequires:   doxygen
BuildArch:      noarch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root

%description
Conversion between Traditional and Simplified Chinese


%prep
%setup -q -n %{name}-%{version}

%define _binaries_in_noarch_packages_terminate_build   0
# >> setup
# << setup

%build

# >> build pre

make %{?jobs:-j%jobs}
# << build pre



# >> build post
# << build post

%install
mkdir -p $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT
# >> install post
# << install post

%pre
# >> pre
# << pre

%preun
# >> preun
# << preun

%files
%defattr(-,root,root,-)
/usr/share/opencc
/usr/include
/usr/lib/
/usr/bin/

# >> files
# << files
